### ISSUE TITLE
Route-level timeout

### ISSUE THREAD

**Issue by mm-gmbd** [electricimp/Rocky#14]
The ability to configure the timeout on a route-level basis (that would take precedence over the global-level timeout) would be very handy. There are some requests that require an extended period of time on the device before completion is successful, and I'd rather not have to extend the timeout for the entire application for the purpose of serving a single route, and using the route-level `onTimeout()` handler to catch/hold the response seems like a hacky way to do it, too.

**Comment by mm-gmbd** [comment]
Submitted PR #15 for review

**Comment by betzrhodes** [comment]
pull request accepted and integrated into v1.3.0

**Comment by mm-gmbd** [comment]
Thanks!

**Comment by betzrhodes** [comment]
Your welcome.  Thanks for contributing.
