### ISSUE TITLE
Unhandled exceptions in handlers

### ISSUE THREAD

**Issue by dbukhmastov** [electricimp/Rocky#25]
Errors in handlers(Rocky.onTimeout, Rocky.onNotFound, Rocky.Route.onTimeout) are NOT caught by Rocky.onException, meanwhile errors in handlers(Rocky.authorize, Rocky.onUauthorized, Rocky.Route.authorize, Rocky.Route.onUnauthorized) are caught by Rocky.onException.
#### Tests:
This issue affects 
class: tests/RockyHandlers.agent.test.nut method: testTimeoutException()
class: tests/RockyHandlers.agent.test.nut method: testNotFoundException()
class: tests/RockyRouteHandlers.agent.test.nut method: testTimeoutException()

**Comment by smittytone** [comment]
Should be fixed in 3.0.0
