### ISSUE TITLE
Rocky should be a Singleton!

### ISSUE THREAD

**Issue by ppetrosh** [electricimp/Rocky#35]
This would help to avoid so many runtime issues when someone accidentally creates two Rocky instances and handlers from the first one stop working.

**Comment by terrencebarr** [comment]
Sounds reasonable

**Comment by zandr** [comment]
I can't see a downside to this.

**Comment by blindman2k** [comment]
Let's be honest, we have all done it.
I suggest a global boolean is set in the constructor and checked in the second constructor attempt with an exception thrown if it is set.

**Comment by smittytone** [comment]
Will be added in 3.0.0
