### ISSUE TITLE
Rocky signatures are not case sensitive

### ISSUE THREAD

**Issue by betzrhodes** [electricimp/Rocky#36]
Signatures are not case sensitive. Rocky converts all signatures to lower case. This becomes very evident when using Context.path to match a signature that contains upper case letters. 

```
function handler(context) {
    context.send(200, "OK");
    
    local path = context.path;
    local p2 = split(context.req.path, "/");
    
    server.log("CONTEXT PATH: " + path[1]);
    server.log("REQUEST PATH: " + p2[1]);

    server.log("CONTEXT PATH MATCH: " + (path[1] == "RebootAgent"));
    server.log("REQUEST PATH MATCH: " + (p2[1] == "RebootAgent"));
}

_api.on("GET", "/meter/RebootAgent", handler);
```

When a web request is made using the path "/RebootAgent" the following logs are produced:  
2018-10-18 13:06:12 -07:00 | [Agent] | CONTEXT PATH: rebootagent
2018-10-18 13:06:12 -07:00 | [Agent] | REQUEST PATH: RebootAgent
2018-10-18 13:06:12 -07:00 | [Agent] | CONTEXT PATH MATCH: false
2018-10-18 13:06:12 -07:00 | [Agent] | REQUEST PATH MATCH: true

**Comment by smittytone** [comment]
Will be fixed in 3.0.0
