### ISSUE TITLE
Access control, expose headers

### ISSUE THREAD

**Issue by blindman2k** [electricimp/Rocky#4]
Currently the access control doesn't exposed any headers so CORS prevents anything but the most basic headers from being read when executed from another web server. If we had an array of headers to be exposed they could automatically be exposed in the addAccessControl method.

For example:

``` squirrel
    rocky.addExposedHeader("X-Version");
```

or

``` squirrel
    rocky.setExposedHeaders(["X-Version"]);
```

Would result in:

``` squirrel
    res.header("Access-Control-Expose-Headers", "X-Version");
```

**Comment by cat-haines** [comment]
Rocky.Context already has a method for adding headers, why do we want/need a method _specifically_ for the `Access-Control-Expose-Headers` header?

**Comment by blindman2k** [comment]
Because it needs to be added to the headers of every request, AFAIK. 
An alternative would be a middleware hook before every request where this and any other arbitrary code could be executed before every request handler.

**Comment by cat-haines** [comment]
Going to implement as middleware
