### ISSUE TITLE
Access control, automatic acceptance of preflight check

### ISSUE THREAD

**Issue by blindman2k** [electricimp/Rocky#5]
Sometimes, when a browser executes an ajax request from another server it performs a preflight check by sending the OPTIONS verb to the URL in question. We could automatically support this and respond with the following code:

``` squirrel
        this.on("OPTIONS", "/", function(context) { context.send("OK"); });
        this.on("OPTIONS", "/.*", function(context) { context.send("OK"); });
```

**Comment by cat-haines** [comment]
We're going to implement this as a documentation change: add a CORS section to the README indicating that if you're creating an API for ajax requests, you should add the following handler:

``` squirrel
app.on("OPTIONS", ".*", function(context) { context.send("OK"); });
```
