### ISSUE TITLE
Wildcard support for path signatures

### ISSUE THREAD

**Issue by blindman2k** [electricimp/Rocky#6]
Currently, we support the \* wildcard for the verb in .on() requests to mean "any verb". We should consider supporting the same format for the path signature. This leads to questions of using wildcards instead of regular expressions for other parts of the signature such as /path/\* instead of /path/.\* but I am not sure if that is the right thing to do.

Alternatively we could simply allow the path signature to be optional in which case the wildcard is implied.

**Comment by cat-haines** [comment]
We already support regular expressions for path signatures - do you have some more specific stories or use cases for this feature (is it just a readability thing, etc)

**Comment by blindman2k** [comment]
It is just a readability thing. 

Does anyone have an idea how to combine the two GET paths into one regex?:

``` squirrel
        _path = "/data";
        _rocky.on("GET", _path, callback);
        _rocky.on("GET", _path + "/(.*)", callback);
```

This catches "/data" and "/data/anything" but not "/datatwo".

**Comment by cat-haines** [comment]
Closing as won't fix (as mentioned - regular expressions allow you to have wildcards, etc)
