### ISSUE TITLE
Rocky throws an error when incoming content-type header is <20 bytes

### ISSUE THREAD

**Issue by cat-haines** [electricimp/Rocky#7]
> ```
> Parse error 'slice out of range (line 391)
> ```
> 
> https://github.com/electricimp/Rocky/blob/7add08053ecdfb9d3a5230b598786a045b1e50da/Rocky.class.nut#L149
> 
> \- @imp-gino

**Comment by blindman2k** [comment]
Yep, that's definitely a bug. A quick check of the length at line 163 should fix that. A similar check needs to be made on line 165.

Line 163

``` squirrel
if ("content-type" in req.headers && req.headers["content-type"].slice(0,20) == "multipart/form-data;") {
```

Line 165

``` squirrel
local boundary = req.headers["content-type"].slice(30);
```
